package com.min.zblog.data.entity;
// Generated 2018-8-19 21:26:30 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmArticleTag generated by hbm2java
 */
@Entity
@Table(name = "tm_article_tag", catalog = "zblog")
@IdClass(TmArticleTagKey.class)
public class TmArticleTag implements java.io.Serializable {

	private Long tagId;
	private Long articleId;
	private Date createTime;
	private Date updateTime;
	private Integer jpaVersion;

	public TmArticleTag() {
	}

	public TmArticleTag(Long tagId, Long articleId) {
		this.tagId = tagId;
		this.articleId = articleId;
	}

	public TmArticleTag(Long tagId, Long articleId, Date createTime, Date updateTime, Integer jpaVersion) {
		this.tagId = tagId;
		this.articleId = articleId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.jpaVersion = jpaVersion;
	}

	@Id
	@Column(name = "tag_id", nullable = false)
	public Long getTagId() {
		return this.tagId;
	}

	public void setTagId(Long tagId) {
		this.tagId = tagId;
	}
	
	@Id
	@Column(name = "article_id", nullable = false)
	public Long getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Long articleId) {
		this.articleId = articleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "jpa_version")
	public Integer getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(Integer jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

}
