package com.min.zblog.data.entity;
// Generated 2018-8-19 21:26:30 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.min.zblog.facility.enums.Indicator;

/**
 * TmCategory generated by hbm2java
 */
@Entity
@Table(name = "tm_category", catalog = "zblog")
public class TmCategory implements java.io.Serializable {

	private Long id;
	private Long userId;
	private String name;
	private String description;
	private Integer sort;
	private String icon;
	private Indicator available;
	private Integer count;
	private Date createTime;
	private Date updateTime;
	private Integer jpaVersion;

	public TmCategory() {
	}

	public TmCategory(Long userId, String name, String description, Integer sort, String icon, Indicator available,
			Date createTime, Date updateTime, Integer count, Integer jpaVersion) {
		this.userId = userId;
		this.name = name;
		this.description = description;
		this.sort = sort;
		this.icon = icon;
		this.available = available;
		this.count = count;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.jpaVersion = jpaVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 50, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "sort")
	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	@Column(name = "icon", length = 100)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "available", length = 1)
	@Enumerated(EnumType.STRING)
	public Indicator getAvailable() {
		return this.available;
	}

	public void setAvailable(Indicator available) {
		this.available = available;
	}
	
	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "jpa_version")
	public Integer getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(Integer jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

}
