package com.min.zblog.data.entity;
// Generated 2018-9-27 23:08:00 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmComment generated by hbm2java
 */
@Entity
@Table(name = "tm_comment", catalog = "zblog")
public class TmComment implements java.io.Serializable {

	private Long id;
	private Long articleId;
	private Long rid;
	private Long pid;
	private Long userId;
	private String pnickname;
	private String nickname;
	private String content;
	private Integer favorNum;
	private String ip;
	private String browser;
	private Date createTime;
	private Date updateTime;
	private Integer jpaVersion;

	public TmComment() {
	}

	public TmComment(Long articleId, Long rid, Long pid) {
		this.articleId = articleId;
		this.rid = rid;
		this.pid = pid;
	}

	public TmComment(Long articleId, Long rid, Long pid, Long userId, String pnickname, String nickname, String content,
			Integer favorNum, String ip, String browser, Date createTime, Date updateTime, Integer jpaVersion) {
		this.articleId = articleId;
		this.rid = rid;
		this.pid = pid;
		this.userId = userId;
		this.pnickname = pnickname;
		this.nickname = nickname;
		this.content = content;
		this.favorNum = favorNum;
		this.ip = ip;
		this.browser = browser;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.jpaVersion = jpaVersion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "article_id", nullable = false)
	public Long getArticleId() {
		return this.articleId;
	}

	public void setArticleId(Long articleId) {
		this.articleId = articleId;
	}

	@Column(name = "rid")
	public Long getRid() {
		return this.rid;
	}

	public void setRid(Long rid) {
		this.rid = rid;
	}

	@Column(name = "pid")
	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	@Column(name = "user_id")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "pnickname", length = 30)
	public String getPnickname() {
		return this.pnickname;
	}

	public void setPnickname(String pnickname) {
		this.pnickname = pnickname;
	}

	@Column(name = "nickname", length = 30)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "favor_num")
	public Integer getFavorNum() {
		return this.favorNum;
	}

	public void setFavorNum(Integer favorNum) {
		this.favorNum = favorNum;
	}

	@Column(name = "ip", length = 64)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "browser", length = 128)
	public String getBrowser() {
		return this.browser;
	}

	public void setBrowser(String browser) {
		this.browser = browser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "jpa_version")
	public Integer getJpaVersion() {
		return this.jpaVersion;
	}

	public void setJpaVersion(Integer jpaVersion) {
		this.jpaVersion = jpaVersion;
	}

}
